- .github/workflows/release.yml
NPM packages published to an org are by default private. We need to set a flag to make sure we have a public package.
> Update release github action

- .github/workflows/sync.yml
Change source and target branches for sync of [Simplified circulation-web](http://github.com/NYPL-Simplified/circulation-web).
NYPL has changed their primary [circulation-web](http://github.com/NYPL-Simplified/circulation-web) branch from `master` to `main`.
> Update sync for NYPL main branch change

- src/stylesheets/custom_lists_sidebar.scss
- src/stylesheets/lane_editor.scss
Specifies minimum width for some CSS selectors to prevent columns collapsing when other columns contain long names/titles
This is affecting the custom list manager for several of our libraries.
Manual testing by modifying values in the browser developer tools.
- N/A I have updated the documentation accordingly.
> Avoid some columns collapsing when other columns contain long names/titles.

- CHANGELOG.md
- src/components/ConfigTabContainer.tsx
- src/components/EditableConfigList.tsx
- src/components/Header.tsx
- src/components/IndividualAdminEditForm.tsx
- src/components/IndividualAdmins.tsx
- src/components/ServiceEditForm.tsx
- src/components/SitewideSettingEditForm.tsx
- src/components/__tests__/ConfigTabContainer-test.tsx
- src/components/__tests__/EditableConfigList-test.tsx
- src/components/__tests__/Header-test.tsx
- src/components/__tests__/IndividualAdminEditForm-test.tsx
- src/components/__tests__/IndividualAdmins-test.tsx
1. On the System Configuration screen, remove the Analytics tab for librarians and library managers, and add the Admins tab.
2. Making the Admins tab available to librarians revealed some problems. Even though librarians (non-managers) don't have the ability to do any useful edits, the UI implied that they could. The Admins tab is now properly read-only for librarians, with the following changes:
1. The Create button was present. Librarians are actually able to create users, but can't assign them to any roles in any libraries, so the users can't log in. The Create button is now not shown.
2. Edit buttons were present for each user. This opened a form where all the inputs were disabled. The Edit buttons are now replaced with View buttons.
3. Clicking the Edit (now View) button for a user …
> Update config tabs for librarians and library managers.

- src/stylesheets/announcements.scss
- src/stylesheets/book_details_container.scss
- src/stylesheets/book_details_tab_container.scss
- src/stylesheets/catalog_overrides.scss
- src/stylesheets/custom_list_editor.scss
- src/stylesheets/editor.scss
- src/stylesheets/entry_points_container.scss
- src/stylesheets/facets.scss
- src/stylesheets/global.scss
- src/stylesheets/header.scss
- src/stylesheets/self_tests.scss
- src/stylesheets/troubleshooting.scss
This changes the button and link color to Palace dark blue, with a hover color that is a lighter shade of that blue. Previously, the normal color was the lighter shade, and the hover color was Palace dark blue.
This was requested to make the styling better match the Palace style guide.
See comments in this Notion ticket: https://www.notion.so/lyrasis/Update-CM-with-Brand-guidance-88976ea09252447998779b4bbeb2fdeb 
I browsed around the circulation-admin UI, verifying that buttons and links that are blue are normally dark, and become light when hovered over.
> Change button/link color to Palace dark blue.

- CHANGELOG.md
- src/components/EditableConfigList.tsx
- src/components/Header.tsx
- src/components/__tests__/EditableConfigList-test.tsx
- src/components/__tests__/Header-test.tsx
@jonathangreen observed that when opening the System Configuration screen, two simultaneous requests are sent to /admin/libraries. This ensures that only one request occurs.
This happens because the Header component wants to load the libraries to populate the library selection dropdown, and the Libraries list (which is the first tab, so automatically opens) also wants to load the libraries.
When a libraries fetch starts, the app state is updated, so this just adds checks to both the Header and Libraries components: If a fetch is in flight, another one is not started.
This reduces load on the server, since the libraries request can be expensive to fulfill.
- Log in to the admin UI.
- Open the Network panel in the developer tools.
- Click on System Configuration.
Verify that:
- Only one …
> Prevent redundant /admin/libraries requests when opening config screen.

- CHANGELOG.md
- src/components/BookDetailsTabContainer.tsx
- src/components/Header.tsx
- src/components/__tests__/BookDetailsTabContainer-test.tsx
- src/components/__tests__/Header-test.tsx
This removes the Complaints tab from the header and the book details screen.
Before:
After:
We are, at least temporarily, removing the "Report a Problem" feature from the apps so we need to remove the related Complaints feature from the Palace Manager Admin UI.
Notion: https://www.notion.so/lyrasis/Remove-Complaints-feature-from-Palace-Manager-Admin-UI-40d74cce55fc43e0900085cf83cb69c9
Tested by opening the Admin UI, and opening book details screens. The Complaints tab was verified to no longer appear in the header, nor in the book details. This is a view-only change -- actions and reducers that relate to complaints were not removed, to make it easy if we ever want to add this feature back -- so the impact is pretty limited.
Unit tests were updated to no longer expect the Complaints tabs …
> Remove complaints

- CHANGELOG.md
- src/components/EditableConfigList.tsx
- src/components/__tests__/EditableConfigList-test.tsx
- src/stylesheets/config_tab_container.scss
When editing lists of configuration items in the System Configuration tabs, the count of items in the list is now displayed. The count is shown above the list, on the same line as the Create New button.
Screenshots:
The number of configured libraries is commonly requested. Adding the count at the top of the Library Configuration screen in the CM saves time for the Implementation Team.
It seemed useful (or at least not harmful) to have counts on all the lists, so I added the count to the component used for all configuration lists, not just the library list.
I tested by clicking through all the System Configuration tabs, and validated that the count appears, and is correct. A unit test has been added to verify that a count is rendered on lists.
> Add count to system configuration lists.

- CHANGELOG.md
- src/components/Header.tsx
- src/components/__tests__/Header-test.tsx
This makes the Patrons link in the header only visible to users who are system administrators. Users who are only library managers no longer see the link.
The Patrons link is only used to reset Adobe IDs, and may be confusing to most users, including library managers. This makes the link only visible to system administrators, who will probably know how to use it.
Notion: https://www.notion.so/lyrasis/Hide-Patrons-tab-from-the-Collection-Manager-for-administrator-and-user-accounts-eb4c97f5380e4c20b40a761a702766a1
Tested by logging in as a system administrator, and verifying that the Patrons link is visible; and logging in as a user who is not a system administrator, and verifying that the Patrons link does not appear.
Unit tests have been updated to verify that the link is rendered for …
> Limit visibility of Patrons link to system admins.

- CHANGELOG.md
- src/components/Header.tsx
- src/components/__tests__/Header-test.tsx
This moves the Dashboard link in the header to be the first item, instead of being several items deep in the list.
Currently, the Dashboard option is six items deep in the menu bar at the top. It would be much more obvious and convenient for library staff members if Dashboard is moved to be the first option in that list.
Notion: https://www.notion.so/lyrasis/Move-Dashboard-to-the-first-menu-option-available-in-the-tabs-at-the-top-of-screen-1d04bbefc4724b199e4391510b17c4fd
Tested by logging in as a system admin and a librarian, and verifying that Dashboard appears first in the header when a library is selected. When a library is not selected (e.g. on the System Configuration tab), there should be no change.
Unit tests have been updated to expect Dashboard to be the first link.
> Move Dashboard to be the first link in the header.

- CHANGELOG.md
- src/components/BookDetails.tsx
- src/components/__tests__/BookDetails-test.tsx
- src/stylesheets/book_details_tab_container.scss
This removes the circulation links (Borrow, Download, Read buttons) from the book details page. The count of copies available is retained.
I previously mentioned making this change in a fork of [NYPL-Simplified/opds-web-client](https://github.com/NYPL-Simplified/opds-web-client), but I realized that there was a good way to do it in just this repo.
Screenshot:
This reduces unneeded complexity in the Admin UI, as there is no in-browser reader for EPUB books.
Notion: https://www.notion.so/lyrasis/Hide-Borrow-button-from-Admin-User-accounts-68fbcb4d0a3f44fc942a247a7bc08e40
- Open some book details, using users with different permission levels.
- Verify that for all books and all users, there is no "Borrow", "Download", or "Read" button above the number of copies available.
> Remove circulation links from book details.

- CHANGELOG.md
- src/components/CustomListEditor.tsx
- src/components/__tests__/CustomListEditor-test.tsx
- Previously, when editing a list, the save button was only enabled when a book was added from a search. Now, the save button is enabled when either a source collection is selected, or a book is added from a search.
- The logic to determine if the save button should be enabled didn't really make sense to me -- possibly some stuff was left over from older versions, and isn't relevant now -- so I rewrote it to be much simpler.
- When writing new tests, I ran into some places where there were missing null checks on variables, so I fixed those.
Note: I don't like the implementation of the list editing component. It has a lot of internal state that makes it very hard to test without directly setting the state in tests, which breaks the encapsulation. I don't have time to refactor the component …
> Enable list save button when a collection is selected.

- CHANGELOG.md
- package-lock.json
- package.json
- src/__tests__/actions-test.ts
- src/actions.ts
- src/components/CustomListEditor.tsx
- src/components/CustomListEntriesEditor.tsx
- src/components/CustomListSearch.tsx
- src/components/CustomLists.tsx
- src/components/__tests__/CustomListEditor-test.tsx
- src/components/__tests__/CustomListEntriesEditor-test.tsx
- src/components/__tests__/CustomListSearch-test.tsx
- src/components/__tests__/CustomLists-test.tsx
- src/reducers/__tests__/customListEditor-test.ts
- src/reducers/customListEditor.ts
- src/reducers/index.ts
- tsconfig.json
- tslint.json
This refactors the `CustomListEditor`, `CustomListEntriesEditor`, and `CustomListSearch` components to:
- Make them stateless.†
- Remove data manipulation functions that are better implemented outside of the view layer.
The state that was being kept by these components is now lifted up into the Redux store. Several new action creators have been added to represent the actions users can perform on the custom list editor form. A new `customListEditor` reducer handles these actions, and updates the state accordingly. The view components are now pure functions that accept props (pulled from the Redux state), and return a rendered DOM.
† There is still one tiny bit of state in `CustomListEntriesEditor`, the source of a drag while a drag-and-drop is in progress. This can be moved later, if we …
> Refactor CustomListEditor and related components.

- CHANGELOG.md
- src/stylesheets/advanced_search.scss
- src/stylesheets/custom_list_entries_editor.scss
- src/stylesheets/global.scss
This fixes a few styling issues:
- When the LastPass browser extension is installed and enabled, a large block of whitespace appears at the top of the screen, making the content invisible without scrolling down. This started happening with a recent update to the LastPass extension, which inserts a top-level `div` in the web page being viewed. The CSS was not expecting this extra `div` to exist.
- The advanced search input fields were misaligned in Firefox.
- There were unnecessary bullets appearing on the list items in the search results and list entries.
The admin UI appears to be completely broken in browsers where the LastPass extension is enabled. The UI is usable after scrolling down to make it visible, but it's hard to discover you have to do that.
Notion: …
> Fix styling issues.

- CHANGELOG.md
- src/reducers/__tests__/customListEditor-test.ts
- src/reducers/customListEditor.ts
This sends the media type and sort order parameters when saving auto updating lists. Previously, only the advanced search query was sent.
This allows the CM to exactly reproduce the search that was configured by the user when editing a list in the admin UI. In the UI, the user is able to select a media type (all, book, audio) and a sort order (relevance, title, author), in addition to an advanced search query. These all affect the search results. (Somewhat non-intuitively, setting the sort order to title or author changes the search results, because a relevance cut-off is automatically applied.)
This finishes off https://www.notion.so/lyrasis/Admin-UI-Automatically-add-new-titles-to-list-when-they-match-search-parameters-b86ceeffe55d4628b822e661eb992544. (There is some discussion of this …
> Save search parameters with auto-updating lists.

- CHANGELOG.md
- src/__tests__/actions-test.ts
- src/actions.ts
- src/components/AnnouncementForm.tsx
- src/components/ConfigTabContainer.tsx
- src/components/SitewideAnnouncements.tsx
- src/components/__tests__/AnnouncementForm-test.tsx
- src/components/__tests__/ConfigTabContainer-test.tsx
- src/components/__tests__/SitewideAnnouncements-test.tsx
- src/interfaces.ts
- src/reducers/index.ts
- src/reducers/sitewideAnnouncements.ts
- src/stylesheets/announcements.scss
This adds a Sitewide Announcements configuration tab, where system administrators can configure announcements for all libraries on a CM.
For consistency, this uses the same UI components as the Announcements section in the library configuration screen, and it works identically. I'm not a fan of the UX of those components, but I'm not rewriting them in this PR; that can be a future task. I also noticed some weird but non-blocker bugs in those components, but those can also be addressed in future work.
This allows administrators to send announcements to all users on a CM when needed, for example to announce outages.
Notion: https://www.notion.so/lyrasis/Add-to-front-end-Add-ability-for-super-admins-to-send-mass-announcements-to-all-libraries-configure-36d71b64670f42bc9a8a96d7cca2f025
- Log …
> Implement global announcements.

- src/components/CustomLists.tsx
- src/components/__tests__/CustomLists-test.tsx
This fixes a bug in #42. When a library only has lists that it does not own, there is an error opening the Lists screen, and nothing appears.
Currently, when the Lists screen is opened, the first list in the sidebar is automatically opened for editing (or if there are no lists, the form to create a new list is opened). With #42, the lists in the sidebar are by default filtered to show only owned lists, so it's possible for lists to exist, but for none to appear in the sidebar when the Lists screen is first opened. The code that opens the detail view doesn't expect this.
Now, when there are lists, but none are owned, the form to create a new list is opened.
Also, the function that was named `sortedLists` has been changed to `filteredSortedLists` to make it clear that it both filters and …
> Fix error loading lists page when there are no owned lists.

- src/__tests__/actions-test.ts
- src/actions.ts
- src/reducers/__tests__/createFetchEditReducer-test.ts
- src/reducers/createFetchEditReducer.ts
The clears the custom list entries from the Redux store when opening a different list or creating a new list.
Specifically, the `openCustomListEditor` action creator now dispatches the `CUSTOM_LIST_DETAILS_CLEAR` action in addition to the `OPEN_CUSTOM_LIST_EDITOR` action, and a handler for `CUSTOM_LIST_DETAILS_CLEAR` has been implemented that restores the initial (empty) state.
When a list is edited, its entries are loaded, and stored in the Redux store. When a different list is opened, or a new list is created, the entries were not being cleared. This didn't cause an evident problem if a different list was opened, because its entries would be loaded immediately, replacing the old entries. But when a new list is created, there are no entries to load, so the continued existence of the …
> Clear list entries from state when opening a new list.

- src/components/CustomListEditor.tsx
- src/components/CustomListEntriesEditor.tsx
- src/components/CustomLists.tsx
- src/components/__tests__/CustomListEditor-test.tsx
- src/components/__tests__/CustomListEntriesEditor-test.tsx
This makes a few changes to the breadcrumb trail that is displayed on the book detail page when it is opened from the list editor:
- When the book detail page is opened from the list editor while creating a new list, don't show breadcrumbs. Since the new list hasn’t been saved, there is nowhere for the breadcrumb to go.
- When the book detail page is opened from the list editor while editing an existing list, use the saved list name to build the breadcrumb trail, not the current unsaved name. The current name may have been changed, and therefore would not be known to the CM yet.
- While editing an existing list, when the View Details button is clicked from a search result (as opposed to a list entry), don’t show a breadcrumb trail on the book detail page. Showing the list name in the …
> Fix breadcrumb issues when opening book details from the list editor.

- src/components/LaneCustomListsEditor.tsx
- src/components/LaneEditor.tsx
- src/components/__tests__/LaneCustomListsEditor-test.tsx
- src/components/__tests__/LaneEditor-test.tsx
- src/stylesheets/lane_editor.scss
This adds the ability to filter the lists that are shown when editing a lane. The options are to show only the lists owned by the current library (the default), only lists shared by other libraries, or all lists.
It also adds a share icon to lists that are owned by other libraries, to make them easy to differentiate.
This makes it easier for librarians to find their own lists, vs. lists shared by other libraries, when creating lanes. 
Notion: https://www.notion.so/lyrasis/Add-filtering-options-to-lists-when-editing-a-lane-08b679fb44124a6aa9cd8743a003a43c
1. In one library, create a list, and share it.
2. In a second library, create a list that is not shared.
3. In the second library, create a new Lane.
In Available Lists, the Show menu should have "Owned" selected. Only the owned list …
> Add list filtering to lane editor.

- CHANGELOG.md
- src/reducers/__tests__/customListEditor-test.ts
- src/reducers/customListEditor.ts
This sets the `isModified` and `isSearchModified` properties in the custom list editor state correctly when the `CUSTOM_LISTS_LOAD` action is fired, following the reload of a custom list after it has been saved. Since the list has just been saved, `isModified` and `isSearchModified` should become false, but these properties were not being updated.
Because of this, the list status was not changing after save, and the Save button was remaining enabled. Notion: https://www.notion.so/lyrasis/Auto-updating-list-status-is-not-updated-after-save-d5ea52ff27ff463085642df0ce5d6263
1. Create a new list.
2. Add a search filter.
In the List Entries box, the Status should be “New”.
3. Save the list.
In the List Entries box, the Status should be “Initializing”.
The Save button at the top of the page …
> Fix incorrect modified state in custom list editor following save.

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/EntryPointsContainer.tsx
This removes the Borrow button from the catalog list view. It upgrades opds-web-catalog to 1.0.0, which allows us to show or hide the circulation links by setting a prop.
Before:
After:
The circulation functions are complicated to support in the admin UI, and there is no built-in reader, so we are removing them.
Notion: https://www.notion.so/lyrasis/Hide-Borrow-button-when-viewing-titles-in-list-view-after-opening-a-lane-in-the-Collection-Manager-b00a7e7bac244b57a6abf2a737f42510
In the catalog, click on a lane, and click the list view button at the top. No Borrow buttons should appear in the list, as in the above screenshot.
> Remove borrow button from catalog list view.

- tsconfig.json
This fixes a TypeScript compilation error that occurs because we now have both Mocha and Jest in the project. Both projects declare certain global variables with the same names, such as `describe`, `it`, and `test`, but different types. The fix configures TypeScript not to check every type definition file in `node_modules/@types`. Instead, it only checks the types that are imported by our source files. See https://www.typescriptlang.org/tsconfig#skipLibCheck.
Since we added Jest tests, the `npm run build-docs` script produces errors like:
```
node_modules/@types/mocha/index.d.ts:2733:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'test' must be of type 'It', but here has type 'TestFunction'.
2733 declare var test: Mocha.TestFunction;
~~~~ …
```
> Prevent duplicate variable declaration error.

- src/components/AdvancedSearchBuilder.tsx
- src/components/AdvancedSearchFilterInput.tsx
- src/components/EditableInput.tsx
- src/stylesheets/colors.scss
- src/stylesheets/global.scss
- tests/jest/components/AdvancedSearchBuilder.test.tsx
- tests/jest/components/EditableInput.test.tsx
This adds a placeholder and help text to the advanced search form when the publication date field is selected. More generally, it allows a placeholder and help text to be associated with any advanced search field. It also changes the color of placeholder text to gray (instead of black) throughout the app. Finally, it improves accessibility by assigning aria labels to a couple of fields that did not have labels, and associating descriptions with input fields in an accessible way.
Publication dates must be entered in a specific format for search, but there was no indication of this to users.
Notion: https://www.notion.so/lyrasis/Add-descriptive-text-for-publication-date-format-in-list-search-7f3c6854b9254008a4bef70672ca001a#382051252fc24ec6a7b89cdb3cc28337
- Edit a list
- In the "Search for …
> Add help text to publication date search field.

- CHANGELOG.md
- src/components/ContextProvider.tsx
- src/components/IndividualAdminEditForm.tsx
- tests/jest/components/IndividualAdminEditForm.test.tsx
- tests/jest/testUtils/renderWithContext.tsx
This fixes a bug where role checkboxes remained checked after saving a new user in the Admins tab. The code stores references to the checkbox components on the form, and clears them after save, but this only worked if there was a single library. If there is more than one library, the code only kept references to the checkboxes for the last library in the list, so only those checkboxes were cleared. The fix stores references to the checkboxes for all libraries, so they can all be cleared.
(The whole notion of storing references to the checkboxes and imperatively calling clear() on them is pretty cringey, but I'm not doing a big refactor now.)
In order to simplify writing a test for the fix, a new test utility function has been added that automatically wraps some JSX in a `ContextProvider` …
> Clear role checkboxes after saving a new user.

- src/components/IndividualAdminEditForm.tsx
- src/components/__tests__/IndividualAdminEditForm-test.tsx
The CM now considers passwords to be required and not optional. This updates the UI so that the password field shows the "Required" text.
See: https://github.com/ThePalaceProject/circulation/pull/801
I just checked the form in the web interface. All of the real changes happened in the CM.
> Mark password field as required

- CHANGELOG.md
- src/components/Lane.tsx
- src/components/LaneEditor.tsx
- src/components/Lanes.tsx
- src/components/__tests__/Lane-test.tsx
- tests/jest/components/Lane.test.tsx
- tests/jest/components/LaneEditor.test.tsx
This allows automatically generated lanes to be renamed.
- In the Lanes sidebar, every lane now has an edit button, whether it's custom or automatically generated.
- In the lane editor, automatically generated lanes can only be renamed and made visible/invisible. Other functions are not available: deleting, adding/removing lists, and inheriting restrictons from the parent.
The included tests contain examples of using Jest mocks with React Testing Library to achieve something similar to Enzyme's shallow rendering, which allows isolating tests to a single component.
Libraries have requested the ability to rename the automatically generated lanes. Notion: https://www.notion.so/lyrasis/Admin-UI-Add-ability-to-rename-a-default-lane-name-in-the-CM-4b42fd3a308947a7907442d176447de2
- Run using …
> Allow automatically generated lanes to be renamed.

- src/components/CirculationEventsDownloadForm.tsx
- src/components/__tests__/CirculationEventsDownloadForm-test.tsx
- Removes option to request circulation events by location.
- Also removes the drop-down for choosing between "All Events" or "Events By Location", since "All Events" is the only remaining option. The behavior now is to fetch all events for the provided date range.
- Removes tests specific to the events by location functionality.
The "locations" implementation is specific to one non-Palace library and caused confusion to users. [[Notion](https://www.notion.so/lyrasis/Admin-UI-Remove-Events-by-Location-functionality-when-downloading-CSV-16b1cbbfe39e44e5af191cadcad92379?pvs=4)]
- Manually tested in local development environment.
- [CI tests for this branch](https://github.com/ThePalaceProject/circulation-admin/actions/runs/4522384105/jobs/7964809560) passed.
> Removes option to request circulation events by location.

- webpack.dev-server.config.js
During development, a local dev server can be run that proxies requests to a remote back-end, using the command `npm run dev-server -- --env=backend={url}`. The local proxy currently rewrites HTML and OPDS responses, changing URLs that point to the back-end to point to the local proxy, so that all requests from the UI will go through the proxy.
This enables rewriting of OpenSearch description responses as well, so that responses of type `application/opensearchdescription+xml` will have URLs that point to the back end changed to point to the local proxy.
When running the dev server, catalog searches were broken, because they were going to an incorrect URL. Rewriting the  OpenSearch description to point to the correct local URL fixes this.
- Run `npm run dev-server -- …
> Fix catalog search error when running dev-server.

- src/reducers/__tests__/customListEditor-test.ts
- src/reducers/customListEditor.ts
- tests/jest/components/CustomLists.test.tsx
This adds the `language=all` query parameter to all custom list searches.
Only English titles were being returned in custom list search results.
JIRA: https://ebce-lyrasis.atlassian.net/browse/PP-80
- Run `npm run dev-server -- --env=backend=https://minotaur.dev.palaceproject.io`
- Go to http://localhost:8080/admin
- Log in using minotaur credentials
- Open the Lists screen for Minotaur Test Library
- Create a new list
- In Works to Include, search for _title contains jane eyre_
A French title ("Jane Eyre ou Les Mémoires d'une institutrice") and a German title ("Jane Eyre, die Waise von Lowood") should be included in the results.
- Add _language equals french_ to the search filters
The results should now contain only the French title.
- Delete the _language equals french_ filter
The …
> Add language=all param to custom list searches.

- src/actions.ts
- src/components/Collections.tsx
- src/reducers/collectionLibraryRegistrations.ts
- src/reducers/index.ts
- src/reducers/registerLibraryWithCollection.ts
Remove the register libraries handlers.
JIRA: [PP-241](https://ebce-lyrasis.atlassian.net/browse/PP-241)
The changes in https://github.com/ThePalaceProject/circulation/pull/1276 removed the `collection_library_registrations` endpoint, so the admin UI is displaying an error when trying to access it. 
Minotaur has the CM changes deployed, so I was testing against: 
https://minotaur.dev.palaceproject.io
[PP-241]: https://ebce-lyrasis.atlassian.net/browse/PP-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove collection library registrations (PP-241)

- src/actions.ts
- src/components/DashboardPage.tsx
- src/components/QuicksightDashboard.tsx
- src/components/QuicksightDashboardPage.tsx
- src/index.tsx
- src/interfaces.ts
- src/stylesheets/quicksight-dashboard.scss
- tests/jest/components/QuicksightDashboard.test.tsx
```
nvm install 18
nvm use 18
npm run dev-server -- --env=backend=https://minotaur.dev.palaceproject.io
```
Once you've logged in, to see the dashboard you need to go to:
http://localhost:8080/admin/web/quicksight
The URL is not exposed in the App (since I don't think it is quite ready for prime time).
https://ebce-lyrasis.atlassian.net/browse/PP-517
Added unit test.
Tested it manually.
> Add quicksight dashboard

- src/components/InputList.tsx
- src/components/__tests__/InputList-test.tsx
- Fixes a check and a default value in the code that filters already-selected options from the list available options for `menu` settings.
- Adds a test that fails without this change, but passes with it.
- Some typing fixes in unrelated parts of the affected file, in order to appease `eslint`.
The bug resulted in no options being available for selection if none were already selected.
[Jira [PP-1022](https://ebce-lyrasis.atlassian.net/browse/PP-1022)]
- Manually tested in a local development environment.
- Added a new confirmation test.
- N/A I have updated the documentation accordingly.
[PP-1022]: https://ebce-lyrasis.atlassian.net/browse/PP-1022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Settings `menu` items unavailable when none already selected. (PP-1022)

- src/components/AdvancedSearchBuilder.tsx
- src/components/AdvancedSearchFilterInput.tsx
- src/components/__tests__/AdvancedSearchFilterInput-test.tsx
- src/stylesheets/advanced_search.scss
Add a new filter to the list search that allows filtering on `fiction` and `nonfiction`. If the new filter is selected, the input is replaced with a select list, so that the values you can enter are restricted to `fiction` and `nonfiction` since these are the only two valid values for the field. 
Any feedback on this one would be great. It does accomplish what is asked in the ticket, and I think it works from the user perspective, in my testing at least. I only know enough to be dangerous about react though, so there may be better ways to accomplish what I'm doing here.
Would like to be able to filter custom lists by `fiction` status. See PP-1110.
Tested against gorgon running the admin interface locally with the blackstone collection.
> Add fiction list filter (PP-1110)

- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- .github/workflows/sync.yml
- .github/workflows/test-and-tag.yml
- .github/workflows/test.yml
- Updates the versions of some GitHub actions in our workflows.
- Also allows the `Test` workflow run on any push, rather than just on PRs.
I was having some trouble with hangs on the `test.yml` workflow and I was also seeing errors like this in the workflow logs:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
[Jira [PP-1285](https://ebce-lyrasis.atlassian.net/browse/PP-1285)]
- Some testing locally with [`act` v0.2.62](https://github.com/nektos/act).
- Some parts need to be verified on GitHub.
[PP-1285]: https://ebce-lyrasis.atlassian.net/browse/PP-1285?atlOrigin=eyJpIjoiNWRkNTljNz …
> Update some GitHub action versions. (PP-1285)

- src/components/EditableInput.tsx
- src/components/InventoryReportRequestModal.tsx
- src/components/ProtocolFormField.tsx
- src/components/__tests__/EditableInput-test.tsx
- Fix configuration settings components to allow a zero value.
- Added some new tests.
- Also, fixed an unrelated style bug in the `InventoryReportRequestModal` component.
Because zero is `falsy` in JS, using it as a value for our configuration settings resulted in:
- an unexpected value being displayed above the configuration setting with the zero value and
- the the zero value not being displayed in the input control.
[Jira [PP-1353](https://ebce-lyrasis.atlassian.net/browse/PP-1353)]
- Manually tested the UI locally.
- [CI tests for associated branch](https://github.com/ThePalaceProject/circulation-admin/actions/runs/9391773810) passed.
[PP-1353]: https://ebce-lyrasis.atlassian.net/browse/PP-1353?atlOrigin=eyJpI …
> Fix configuration settings to allow a zero value. (PP-1353)

- webpack.dev-server.config.js
Let's the `dev-server` properly handle redirects to relative URLs.
Previously, redirects to relative URLs cause the `dev-server to crash like this:
```
node:internal/errors:496
ErrorCaptureStackTrace(err);
^
TypeError [ERR_INVALID_URL]: Invalid URL
at new NodeError (node:internal/errors:405:5)
at new URL (node:internal/url:676:13)
at rewriteLocationHeader (/Users/Shared/src/tpp/circulation-admin/webpack.dev-server.config.js:70:25)
at /Users/Shared/src/tpp/circulation-admin/webpack.dev-server.config.js:176:9
at IncomingMessage.<anonymous> (/Users/Shared/src/tpp/circulation-admin/node_modules/http-proxy-middleware/dist/handlers/response-interceptor.js:24:57)
at IncomingMessage.emit (node:events:529:35)
at endReadableNT (node:internal/streams/readable:1400:12)
at …
```
> dev-server handles relative redirects without crashing.

- src/components/BookDetailsContainer.tsx
- src/components/BookDetailsEditor.tsx
- src/components/BookDetailsTabContainer.tsx
- src/components/__tests__/BookDetailsContainer-test.tsx
- src/components/__tests__/BookDetailsEditor-test.tsx
- src/components/__tests__/BookDetailsTabContainer-test.tsx
- tests/jest/components/BookEditor.test.tsx
Changes the Book Editor to not show book suppression ("Hide" / "Restore") buttons if the admin user is not a manager / administrator for the active library.
While testing admin UI functionality for hidden books on PP-1463, I noticed that we have been showing the buttons for any admin user. That could lead to a librarian- / user-level admin clicking the button, but eventually receiving a not authorized message.
It is better to just not show the button in the first place.
[Jira [PP-1463](https://ebce-lyrasis.atlassian.net/browse/PP-1463)]
- Manually tested in local dev environment.
- Existing tests updated.
- New tests for functionality.
- [CI tests for associated branch](https://github.com/ThePalaceProject/circulation-admin/actions/runs/10062063572) pass.
- N/A - I have updated the …
> Hide suppression unless library administrator (PP-1463)

- src/components/ContextProvider.tsx
- src/components/InventoryReportRequestModal.tsx
- src/components/LibraryStats.tsx
- src/context/appContext.ts
- tests/jest/context/AppContext.test.tsx
Adds context hooks for many of the properties provided by the current, legacy context provider in the `ContextProvider` component. With this change, the `ContextProvider` component injects a provider for the new `AppContext` into the component tree, so we don't need to account for another component in the app tree or in test wrappers.
- Provide a migration path away from legacy context provider.
- Make it easier to write some business logic hooks.
[Jira [PP-1572](https://ebce-lyrasis.atlassian.net/browse/PP-1572)]
- Manually tested locally with the dev-server.
- New and existing tests pass locally. Existing tests did not need to be modified.
- [CI tests for associated branch](https://github.com/ThePalaceProject/circulation-admin/actions/runs/10289315684) passed.
- N/A - I have updated the …
> Introduce modern context provider and hooks (PP-1572)

- webpack.common.js
Fixes issues rendering Font Awesome fonts.
Fonts were not rendering.
[Jira [PP-1513](https://ebce-lyrasis.atlassian.net/browse/PP-1513)]
- Tested locally via dev-server against development server.
- [CI tests](https://github.com/ThePalaceProject/circulation-admin/actions/runs/10411305910) pass.
[PP-1513]: https://ebce-lyrasis.atlassian.net/browse/PP-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use `asset/resource` type for SASS font support with WebPack 5. (PP-1513)

- src/components/ContextProvider.tsx
- src/components/LibraryStats.tsx
- src/components/StatsUsageReportsGroup.tsx
- src/context/appContext.ts
- src/index.tsx
- src/interfaces.ts
- src/stylesheets/stats.scss
- tests/jest/components/Stats.test.tsx
- Adds the "Usage and Reports" component.
- Builds and styles the overall statistics dashboard layout.
Redesign the library dashboard.
[Jira [PP-1534](https://ebce-lyrasis.atlassian.net/browse/PP-1534)]
- Manually tested via webpack dev-server against dev and staging servers.
- [CI tests](https://github.com/ThePalaceProject/circulation-admin/actions/runs/10426654748) pass.
[PP-1534]: https://ebce-lyrasis.atlassian.net/browse/PP-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Usage/reports component and overall dashboard layout. (PP-1534)

- src/components/StatsUsageReportsGroup.tsx
- tests/jest/components/Stats.test.tsx
- Hides the inventory request description text when the request button is hidden.
- Add verification tests to the test suite.
Having an explanation for a control that is not visible is confusing.
[Jira [PP-1649](https://ebce-lyrasis.atlassian.net/browse/PP-1649)]
- Manually tested locally.
- [CI tests](https://github.com/ThePalaceProject/circulation-admin/actions/runs/10566881352) pass for associated branch.
[PP-1649]: https://ebce-lyrasis.atlassian.net/browse/PP-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Hide inventory report text when button hidden. (PP-1649)

- src/businessRules/roleBasedAccess.ts
- src/components/LibraryStats.tsx
- src/components/StatsCollectionsGroup.tsx
- src/components/StatsUsageReportsGroup.tsx
- src/interfaces.ts
- src/stylesheets/stats.scss
- src/utils/featureFlags.ts
- tests/jest/businessRules/roleBasedAccess.test.ts
- tests/jest/components/Stats.test.tsx
- Adds a feature flag to hide the dashboard statistics link to the QuickSight page from non-sysadmin users.
- Adds business logic and rendering tests for the new functionality.
Need to be able to hide QuickSight dashboard until it is ready to launch.
[Jira [PP-1724](https://ebce-lyrasis.atlassian.net/browse/PP-1724)]
- Manual testing locally.
- [CI tests](https://github.com/ThePalaceProject/circulation-admin/actions/runs/10914450349) pass.
[PP-1724]: https://ebce-lyrasis.atlassian.net/browse/PP-1724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add feature flag for to restrict QuickSight link to sysadmins. (PP-1724)

- src/components/LibraryStats.tsx
- src/components/SingleStatListItem.tsx
- src/components/StatsPatronGroup.tsx
- src/components/__tests__/LibraryStats-test.tsx
- Adds total patron count back to the patron statistics group.
- Updates the tooltip on that statistic with a caveat about how to interpret it.
- Updates tests appropriately.
Responding to customer requests.
[Jira [PP-1744](https://ebce-lyrasis.atlassian.net/browse/PP-1744)]
- Manually tested locally with dev server.
- [CI tests for the branch](https://github.com/ThePalaceProject/circulation-admin/actions/runs/11055211590) pass.
[PP-1744]: https://ebce-lyrasis.atlassian.net/browse/PP-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Restore total patron count. (PP-1744)

- jest.config.js
- src/components/Header.tsx
- src/components/QuicksightDashboardPage.tsx
- src/components/TOSContext.tsx
- tests/__mocks__/fileMock.js
- tests/__mocks__/styleMock.js
- tests/jest/components/QuicksightDashboard.test.tsx
- tests/jest/testUtils/withProviders.tsx
Enables a logo-only (no navigation) header and uses it for the QuickSight Dashboard page.
This PR also fixes up some of the testing infrastructure to allow the jest/react testing library framework tests to:
- support tests that involve (sometimes transitively) the `Footer` component (by adding the `TOSContextProvider` into the component wrapper utilities;
- support tests involving the `Header` component -- specifically, loading the logo via `require` or `import` (by adding mock support for assets).
The key changes are in:
- `src/components/Header.tsx`
- `src/components/QuicksightDashboardPage.tsx`
- `tests/jest/components/QuicksightDashboard.test.tsx`
- Reduce user confusion and accidental navigation.
- Help prevent unnecessary consumption of QuickSight sessions.
[ Jira …
> Logo-only header for QuickSight page. (PP-1720)

- src/components/LibraryStats.tsx
- src/components/StatsPatronGroup.tsx
- src/components/__tests__/LibraryStats-test.tsx
- Remove Total Patrons from the patron stats group.
[Jira [PP-1776](https://ebce-lyrasis.atlassian.net/browse/PP-1776)]
- Manually tested locally.
- [CI tests for branch](https://github.com/ThePalaceProject/circulation-admin/actions/runs/11134123620) pass.
[PP-1776]: https://ebce-lyrasis.atlassian.net/browse/PP-1776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Re-remove Total Patrons from the patron stats group. (PP-1776)

- src/components/ProtocolFormField.tsx
- src/components/__tests__/ProtocolFormField-test.tsx
- tests/jest/components/ProtocolFormField.test.tsx
- Adds a new configuration settings type to handle date settings.
The instigating need is for collection subscription start/end dates; but, the changes here are general and should support any other date input needs.
[Jira [PP-1874](https://ebce-lyrasis.atlassian.net/browse/PP-1874)]
- Manually tested end-to-end with [CM PR# 2153](https://github.com/ThePalaceProject/circulation/pull/2153) configuration settings.
- [CI tests for associated branch](https://github.com/ThePalaceProject/circulation-admin/actions/runs/11727256042) pass.
[PP-1874]: https://ebce-lyrasis.atlassian.net/browse/PP-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add "date-picker" configuration setting type. (PP-1874)

- webpack.dev-server.config.js
Increase the `dev-server` proxy timeout to 120 seconds.
Sometimes the proxy server would time out, especially when performing a catalog request, but sometimes during other functions. These timeouts are not helpful, so bumping up to a high value should eliminate them.
- Tested locally against a library that was consistently causing timeouts.
- This change does not impact any tests in the test suite.
- N/A - All new and existing tests passed.
> Increase WebPack dev-server proxy timeout.

- src/components/CatalogPage.tsx
- src/components/Header.tsx
- src/components/__tests__/CatalogPage-test.tsx
- src/components/__tests__/Header-test.tsx
The code was doing some questionable things to add the `max_cache_age` parameter to URLs. In PP-1962 I found this is causing some issues. We could do some work to fix up how we include the parameter in URLs, but since we are no longer using this parameter in the CM, it doesn't seem worth including it.
Issues I was seeing with this code: 
- max_cache_age would get repeatedly included creating urls like this: `http://localhost:6500/admin/web/collection/GA0011%3Fmax_cache_age%3D0%26max_cache_age%3D0%26max_cache_age%3D0%26max_cache_age%3D0/book/GA0011%2FISBN%2F9780593457580/tab/lists` 🤮 
- Clicking the **Create New List** button in the admin UI would go to a URL like this `http://localhost:6500/admin/web/lists/GA0011?max_cache_age=0&max_cache_age=0&max_cache_age=0&max_cache_age=0/create` …
> Remove max_cache_age parameter (PP-1962)

- src/stylesheets/input_list.scss
In the work editor long lane names were being formatted poorly. Found this while working on PP-1962.
Before this change:
After:
I took a look around the admin interface after making this change, and I don't see any ill effects, but I'm not 100% sure everywhere this style-sheet is used, so its possible there is a better way to approach this.
- Tested locally
> Fix formatting of long lane names (PP-1962)

- src/reducers/__tests__/customListEditor-test.ts
- src/reducers/customListEditor.ts
- Send only `id`s for custom list manual update items in the "entries" and "deletedEntries" properties, rather than including all the metadata associated with the them.
- Exclude items that are already members of the list from the updated "entries" payload.
- Payloads included many unnecessary properties for each list item entry, when only the `id` is needed for additions and deletions.
- The update payload included all loaded current entries, even those that were already members of the list; so, if the use loaded many pages of the list, many unneeded members could be included in the request. This would lead to:
- Larger requests.
- Unnecessary processing.
[Jira [PP-2059](https://ebce-lyrasis.atlassian.net/browse/PP-2059)]
- Manually tested multiple scenarios locally.
- Updated tests.
- …
> Send only IDs for custom list manual update entries. (PP-2050)

- src/components/EditableInput.tsx
- src/components/InputList.tsx
- src/components/ProtocolFormField.tsx
- src/components/__tests__/ProtocolFormField-test.tsx
Provides a simpler and unified approach for hidden configuration settings of all supported types.
Follow on to #144, which supported hidden configuration settings; but did so by attempting to shoehorn all field types into a hidden input field.
[Jira [PP-2090](https://ebce-lyrasis.atlassian.net/browse/PP-2090)]
- Manual testing in my local environment.
- [CI tests for associated branch](https://github.com/ThePalaceProject/circulation-admin/actions/runs/13254548869) pass.
- [N/A - I have updated the documentation accordingly.
[PP-2090]: https://ebce-lyrasis.atlassian.net/browse/PP-2090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Support hidden configuration settings of all field types. (PP-2090)

- package-lock.json
- src/components/AdvancedSearchBuilder.tsx
- src/components/AdvancedSearchFilterInput.tsx
- src/components/__tests__/AdvancedSearchFilterInput-test.tsx
- src/components/__tests__/AdvancedSearchValueFilter-test.tsx
- tests/jest/components/AdvancedSearchBuilder.test.tsx
- tests/jest/components/CustomLists.test.tsx
- tsconfig.json
- Moves custom list search fields from radio buttons to a select pull-down.
- Capitalizes filter field and filter operator labels.
- Updates tests.
- Beginnings of new custom list search UI design.
[Jira [PP-1089](https://ebce-lyrasis.atlassian.net/browse/PP-1089)]
- Manual testing locally.
- Tests updated for change and passing locally.
- [CI tests](https://github.com/ThePalaceProject/circulation-admin/actions/runs/13551316805).
[PP-1089]: https://ebce-lyrasis.atlassian.net/browse/PP-1089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update Custom List search UI. (PP-1089)

- src/components/__tests__/SelfTests-test.tsx
Fixed failing tests related to time zone handling in SelfTests component tests. Updated the test expectations to dynamically compute expected date/time strings based on the actual date object from the test data, rather than hardcoding specific time values.
Previously, the SelfTests component tests were failing because they expected a specific hardcoded time output ("Tests last ran on Tue Aug 07 2018 15:34:54 and lasted 1.75s.") without accounting for the developer's local timezone. This caused tests to fail depending on the timezone of the developer's machine.
The admin UI outputs the localized time, which is the correct behavior, but since the tests were not adjusting for timezones, it meant that anyone running the tests whose local timezone wasn't US eastern would get a test failure. …
> Fix timezone parsing in tests

- .github/workflows/gh-pages.yml
Add a conditional to the gh-pages.yml github action to exclude dependabot.
When merging dependabot PRs to `main` the publish documentation action is failing because dependabot does not have the correct permissions. 
Since dependabot should just be dependency updates, no need to re-publish docs for these PRs anyway. This saves having CI fail every time we merge one a dependabot PR.
Similar fix here: https://github.com/ThePalaceProject/web-opds-client/pull/65
- Hard to test outside of CI
- I took the expression used to check for dependabot PRs from here: https://docs.github.com/en/code-security/dependabot/troubleshooting-dependabot/troubleshooting-dependabot-on-github-actions#troubleshooting-failures-when-dependabot-triggers-existing-workflows
> Ignore dependabot PRs when publishing documentation

- src/components/AdvancedSearchBuilder.tsx
- src/reducers/__tests__/customListEditor-test.ts
- src/reducers/customListEditor.ts
Correctly reset locally added / removed entries when reloading a manual custom list after save, since the associated changes should already be reflected in fresh state just synced from the server. 
- Attempting more than one save of a manual custom list without reloading the page between saves would result in all attempts after the first one to fail.
- If items were added, they would appear both as unsaved additions (indented at the top of the list) and lower down, unindented in the saved items list.
[Jira PP-2447, PP-2076]
- Manually testing via dev-server against a staging instance.
- [CI tests](https://github.com/ThePalaceProject/circulation-admin/actions/runs/15357194217) pass.
> Correctly reset state on manual custom list detail load. (PP-2447, PP-2076)

- package-lock.json
- package.json
- webpack.dev-server.config.js
- Upgrades `webpack-dev-server` from v4 to v5.
- Update dev server proxy code to support new v5 api.
- [Dependabot wanted to upgrade `webpack-dev-server` from v4 to v5](https://github.com/ThePalaceProject/circulation-admin/pull/160); however, when I did some manual compatibility checking, I saw that the proxy server would no longer work. So, the upgrade and the proxy code update had to be coordinated, which Dependabot was not doing
Manual testing in local development environment.
> Upgrade `webpack-dev-server` from v4 to v5. (PP-2687)

- src/components/ContextProvider.tsx
- src/components/__tests__/ContextProvider-test.tsx
- src/components/__tests__/Footer-test.tsx
- src/components/__tests__/LibraryStats-test.tsx
- src/index.tsx
- tests/jest/businessRules/roleBasedAccess.test.ts
- tests/jest/components/CirculationEventsDownload.test.tsx
- tests/jest/components/CustomLists.test.tsx
- tests/jest/components/IndividualAdminEditForm.test.tsx
- tests/jest/components/InventoryReportRequestModal.test.tsx
- tests/jest/components/Stats.test.tsx
- tests/jest/context/AppContext.test.tsx
- tests/jest/testUtils/renderWithContext.tsx
- tests/jest/testUtils/withProviders.tsx
Refactors the `ContextProvider` component to accept a single application `ConfigurationSettings` object in the props, rather than each of its individual members. `ContextProvider`'s Redux `store` prop remains and is unchanged.
I ran into this while working on PP-2768. It was proving challenging to keep types in sync between the legacy `ContextProvider` and other uses of the app configuration settings. There is more work to do within `ContextProvider`, but this was the relatively larger chunk to get the change in and get tests working again.
- Manual testing locally with the dev-server.
- Tests pass [in CI](https://github.com/ThePalaceProject/circulation-admin/actions/runs/16622556097).
> Refactor ContextProvider app config settings.

- src/components/Collections.tsx
- src/components/__tests__/Collections-test.tsx
Adds a confirmation dialog when disassociating a library from a collection.
When a library is disassociated from a collection, all patron loans and holds are immediately removed when the change is saved. The confirmation reduces the risk of accidental disassociation by reminding the user of the repercussions of the action before it is effected.
- Manually tested locally.
- New tests.
- [CI tests](https://github.com/ThePalaceProject/circulation-admin/actions/runs/17078864736) pass.
> Add confirmation when disassociating collection libraries (PP-2408)

- src/components/ServiceEditForm.tsx
- src/components/WithRemoveButton.tsx
- src/components/__tests__/ServiceEditForm-test.tsx
- src/components/__tests__/WithRemoveButton-test.tsx
- Adds support for allowing/disallowing the disassociation of a library from a service integration via the `ServiceEditForm` and its child components. The check is performed synchronously, in real time, when removal is requested via UI interaction.
- Adds documentation to help avoid accidental misuse of the `ServiceEditForm.removeLibrary` method.
The mechanism separates (1) the function of removing a library association from (2) the function of approving that removal.
The default behavior is to allow disassociation. Subclasses of `ServiceEditForm` may override this behavior.
This capability enables future real-time verification that a removal is allowed or intended (e.g., via confirmation dialog).
[Jira PP-2408]
- New and updated tests.
- [CI …
> Add library removal confirmation to service edit form (PP-2408)

- src/components/Collections.tsx
- src/components/ServiceEditForm.tsx
- src/components/WithRemoveButton.tsx
- src/components/__tests__/Collections-test.tsx
- src/components/__tests__/ServiceEditForm-test.tsx
- src/components/__tests__/WithRemoveButton-test.tsx
Use newly-added `isLibraryRemovalPermitted` (instead of `removeLibrary`) to confirm interactive removals of library associations from collections.
NB: This PR is ready for review; however, it depends on #170 for `isLibraryRemovalPermitted`, so this PR should not be merged until that one is landed.
Confirmation popups were rendering for each associated library when the `CollectionEditForm` was being cleared. This is because `removeLibrary` is used both interactively -- when library `Delete` button is clicked -- and non-interactively, when the form is cleared.
[Jira PP-2408]
- Testing in local environment.
- [CI tests](https://github.com/ThePalaceProject/circulation-admin/actions/runs/17103881259) pass.
> Avoid unintended side-effects on non-interactive library disassociations (PP-2408)
